aiServices/fakeNewsClassification/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PredictForm(FlaskForm):
	content = TextAreaField('Content', validators=[DataRequired()])
	submit = SubmitField('Predict')

class PredictBatchForm(FlaskForm):
	file_data = FileField('Upload CSV File')
	submit = SubmitField('Predict Batch')

aiServices/smsSpamClassification/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PredictForm(FlaskForm):
	content = TextAreaField('Content', validators=[DataRequired()])
	submit = SubmitField('Predict')

class PredictBatchForm(FlaskForm):
	file_data = FileField('Upload CSV File')
	submit = SubmitField('Predict Batch')

aiServices/__init__.py
from flask import Flask 

app = Flask(__name__) 
app.config['SECRET_KEY'] = 'e8d28a0e41cd45c770e15c49a132d156'

## load and register blue prints
from aiServices.main.routes import main 
from aiServices.fakeNewsClassification.routes import fakeNewsClassif
from aiServices.smsSpamClassification.routes import smsSpamClassif

app.register_blueprint(main)
app.register_blueprint(fakeNewsClassif)
app.register_blueprint(smsSpamClassif)

aiServices/fakeNewsClassification/routes.py
import os 
from flask import Blueprint, render_template, redirect, url_for, request
from aiServices.fakeNewsClassification.forms import PredictForm, PredictBatchForm
from aiServices.fakeNewsClassification.predict import getPrediction, getBatchPrediction
from aiServices import app 

fakeNewsClassif = Blueprint('fakeNewsClassification', __name__)

@fakeNewsClassif.route("/services/fake-news-classification")
def details():
    return render_template("fakeNewsClassification/details.html", title="fake-news-classification")

@fakeNewsClassif.route("/services/fake-news-classification/predict", methods=['GET', 'POST'])
def predict():
    form = PredictForm()
    fake_score, real_score = None, None
    show_output = False
    if form.validate_on_submit():
        content = form.content.data 
        fake_score = getPrediction(content) *100
        # fake_score = 99.8
        real_score = round(100 - fake_score, 1)
        show_output = True 
        # return redirect(url_for('fakeNewsClassification.predict'))
    return render_template("fakeNewsClassification/predict.html", title="predict", showPredict=False, form=form, fake_score=fake_score, real_score=real_score, show_output=show_output)

@fakeNewsClassif.route("/services/fake-news-classification/predict-batch", methods=['GET', 'POST'])
def predictBatch():
    form = PredictBatchForm()
    fake_count, true_count, output_file_name = None, None, None
    show_output = False
    if form.validate_on_submit():
        file_data = request.files.get('file_data')
        new_file_name = 'input.csv' 
        input_file_path = os.path.join(app.root_path, 'static/upload/' + new_file_name)
        file_data.save(input_file_path)
        output_file_name = 'output.csv'
        output_file_path = os.path.join(app.root_path, 'static/download/' + output_file_name)
        fake_count, true_count = getBatchPrediction(input_file_path, output_file_path)
        # fake_count, true_count = 29, 5
        show_output = True
    return render_template("fakeNewsClassification/predictBatch.html", title="predict-batch", showPredict=True, form=form, fake_count=fake_count, true_count=true_count, show_output=show_output, output_file_name=output_file_name)

aiServices/main/routes.py
from flask import Blueprint, render_template, send_from_directory

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template("main/home.html", title="home")

## url for downloading output csv files
@main.route("/download/<file_name>")
def download_file(file_name):
    return send_from_directory('static/download', file_name)

aiServices/smsSpamClassification/routes.py
import os 
from flask import Blueprint, render_template, redirect, url_for, request
from aiServices.smsSpamClassification.forms import PredictForm, PredictBatchForm
from aiServices.smsSpamClassification.predict import getPrediction, getBatchPrediction
from aiServices import app 

smsSpamClassif = Blueprint('smsSpamClassification', __name__)

@smsSpamClassif.route("/services/sms-spam-classification")
def details():
    return render_template("smsSpamClassification/details.html", title="sms-spam-classification")

@smsSpamClassif.route("/services/sms-spam-classification/predict", methods=['GET', 'POST'])
def predict():
    form = PredictForm()
    spam_score, ham_score = None, None
    show_output = False
    if form.validate_on_submit():
        content = form.content.data 
        # spam_score = getPrediction(content) *100
        spam_score = 99.8
        ham_score = round(100 - spam_score, 1)
        show_output = True 
        # return redirect(url_for('smsSpamClassification.predict'))
    return render_template("smsSpamClassification/predict.html", title="predict", showPredict=False, form=form, spam_score=spam_score, ham_score=ham_score, show_output=show_output)

@smsSpamClassif.route("/services/sms-spam-classification/predict-batch", methods=['GET', 'POST'])
def predictBatch():
    form = PredictBatchForm()
    spam_count, ham_count, output_file_name = None, None, None
    show_output = False
    if form.validate_on_submit():
        # file_data = request.files.get('file_data')
        # new_file_name = 'input.csv' 
        # input_file_path = os.path.join(app.root_path, 'static/upload/' + new_file_name)
        # file_data.save(input_file_path)
        output_file_name = 'output.csv'
        # output_file_path = os.path.join(app.root_path, 'static/download/' + output_file_name)
        # spam_count, ham_count = getBatchPrediction(input_file_path, output_file_path)
        spam_count, ham_count = 29, 5
        show_output = True
    return render_template("smsSpamClassification/predictBatch.html", title="predict-batch", showPredict=True, form=form, spam_count=spam_count, ham_count=ham_count, show_output=show_output, output_file_name=output_file_name)

aiServices/templates/fakeNewsClassification/details.html
{% extends "global/layout.html" %} 

{% block content %} 
<div class="fake-news details">
    <div class="box-1 glass-background">
        <div class="box-1--top">
            <a href="{{ url_for('main.home') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                </svg>
            </a>
            <h2>Real-Fake News Detection</h2>
        </div>
        <div class="box-1--bottom">
            <div class="btn-container glass-background">
                <a href="{{ url_for('fakeNewsClassification.predict') }}" class="btn">Predict</a>
                <a href="{{ url_for('fakeNewsClassification.predictBatch') }}" class="btn">Predict Batch</a>
            </div>
            <ul>
                <li class="text">click <span>Predict</span> button if you wan't to check for single record.</li>
                <li class="text">click <span>Predict Batch</span> button if you wan't to check for multiple records at a time (via upload csv file).</li>
            </ul>
        </div>
    </div>
    <div class="box-2 glass-background">
        <div class="box-2--top">
            <h2>Necessity?</h2>
        </div>
        <div class="box-2--bottom">
            <p class="text">Social media has developed into a platform for communicating current events to the general public. People frequently assume that everything is reported in the news is accurate. However, certain news has a crucial effect on the economy in addition to the people or government. Depending on people's beliefs and the current state of affairs, one news report might cause the curves to shift.</p>
            <p class="text">Therefore, it's important to recognize among legitimate news and fake news. AI enabled Natural Language Processing tools have seized control of the issue and found a solution by enabling us to distinguish between real and false news based on past data. Now that the news is secure, it is!</p>
        </div>
    </div>
</div>
{% endblock content %}

aiServices/templates/fakeNewsClassification/predict.html
{% extends "global/layout.html" %} 

{% block predict %} 
    {% if showPredict %} 
        <a href="{{ url_for('fakeNewsClassification.predict') }}" class="btn btn-invisible">Predict</a>
    {% else %} 
        <a href="{{ url_for('fakeNewsClassification.predictBatch') }}" class="btn btn-invisible">Predict Batch</a>
    {% endif %}
{% endblock predict %}

{% block content %} 
<div class="fake-news predict">
    <div class="box-1 glass-background">
        <div class="box-1--top">
            <a href="{{ url_for('fakeNewsClassification.details') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                </svg>
            </a>
            <h2>Fake-Real News Pediction</h2>
        </div>
        <div class="box-1--bottom">
            <!-- add needs-validation, novalidate inside below form  -->
            <form action="" method="post"> 
                {{ form.hidden_tag() }}
                <div class="text-box">
                    <label for="content">News Content</label>
                    {{ form.content }}
                    <!-- above line is same as below line -->
                    <!-- <textarea id="content" name="content" required></textarea> -->
                </div>
                <input name="submit" type="submit" value="Predict" class="btn btn-outline">
            </form>
        </div>
    </div>
    <div class="box-2 glass-background">
        <div class="box-2--top">
            <h2>Results</h2>
        </div>
        <div class="box-2--bottom">
            {% if show_output %}
                <p><span>{{ real_score }}%</span>REAL</p>
                <p class="other"><span>{{ fake_score }}%</span>FAKE</p>
            {% else %} 
                <p class="default">output<br> will display here</p>
            {% endif %}
        </div>
    </div>
    
</div>
{% endblock content %}

aiServices/templates/fakeNewsClassification/predictBatch.html
{% extends "global/layout.html" %} 

{% block predict %} 
    {% if showPredict %} 
        <a href="{{ url_for('fakeNewsClassification.predict') }}" class="btn btn-invisible">Predict</a>
    {% else %} 
        <a href="{{ url_for('fakeNewsClassification.predictBatch') }}" class="btn btn-invisible">Predict Batch</a>
    {% endif %}
{% endblock predict %}

{% block content %} 
<div class="fake-news predict-batch">
    {% if not show_output %}
        <div class="box-1 glass-background">
            <div class="box-1--top">
                <a href="{{ url_for('fakeNewsClassification.details') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                    </svg>
                </a>
                <h2>Fake-Real News Pediction on Batch Mode</h2>
            </div>
            <div class="box-1--bottom">
                <!-- add  class="needs-validation" novalidate in the below form  -->
                <form action="" method="post" enctype="multipart/form-data"> 
                    {{ form.hidden_tag() }}
                    <label for="file_data">Upload CSV File</label>
                    {{ form.file_data }}
                    <div class="btn-box">
                        <input name="submit" type="submit" value="Predict Batch" class="btn btn-outline">
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <div class="box-1 glass-background results">
            <div class="box-1--top">
                <a href="{{ url_for('fakeNewsClassification.predictBatch') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                    </svg>
                </a>
                <h2>Results</h2>
            </div>
            <div class="box-1--bottom">
                <p>download the csv file predicted on fake vs real news.</p>
                <div class="btn-box">
                    <a href="{{ url_for('main.download_file', file_name=output_file_name) }}" class="btn">Download</a>
                </div>
                <table>
                    <tr>
                        <th>Total Records</th>
                        <th>Fake Records</th>
                        <th>Real Records</th>
                    </tr>
                    <tr>
                        <td>{{ fake_count + true_count }}</td>
                        <td>{{ fake_count }}</td>
                        <td>{{ true_count }}</td>
                    </tr>
                </table>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

aiServices/templates/global/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='scss/css/main.css') }}">
</head>
<body>
    <div class="container">
        <nav>
            <h1><a href="{{ url_for('main.home') }}"><span>ai</span> Services</a></h1>
            {% block predict %} {% endblock predict %}
        </nav>
        {% block content %} {% endblock content %} 
    </div>
</body>
</html>

aiServices/templates/main/home.html
{% extends "global/layout.html" %} 

{% block content %} 
<div class="home">
    <!-- text on image here -->
    <div class="services">
        <div class="service">
            <img src="{{ url_for('static', filename='images/img1.jpg') }}" alt="">
            <div class="mid-btn">
                <a href="{{ url_for('fakeNewsClassification.details') }}" class="btn btn-circle">Read More</a>
            </div>
            <div class="service--body">
                <h5>Real-Fake News Classification System</h5>
                <p>Accuracy = 99.99%</p>
                <!-- content about their respective metrics such as accuracy, precision, recall, F1-Score etc  -->
            </div>
        </div>
        <div class="service">
            <img src="{{ url_for('static', filename='images/img2.jpg') }}" alt="">
            <div class="mid-btn">
                <a href="{{ url_for('smsSpamClassification.details') }}" class="btn btn-circle">Read More</a>
            </div>
            <div class="service--body">
                <h5>SMS Ham-Spam Classification System</h5>
                <p>Accuracy = 98%</p>
                <!-- content about their respective metrics such as accuracy, precision, recall, F1-Score etc  -->
            </div>
        </div>
    </div>
</div>
{% endblock content %}

aiServices/templates/smsSpamClassification/details.html
{% extends "global/layout.html" %} 

{% block content %} 
<div class="sms-spam details">
    <div class="box-1 glass-background">
        <div class="box-1--top">
            <a href="{{ url_for('main.home') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                </svg>
            </a>
            <h2>SMS Ham-Spam Detection</h2>
        </div>
        <div class="box-1--bottom">
            <div class="btn-container glass-background">
                <a href="{{ url_for('smsSpamClassification.predict') }}" class="btn">Predict</a>
                <a href="{{ url_for('smsSpamClassification.predictBatch') }}" class="btn">Predict Batch</a>
            </div>
            <ul>
                <li class="text">click <span>Predict</span> button if you wan't to check for single record.</li>
                <li class="text">click <span>Predict Batch</span> button if you wan't to check for multiple records at a time (via upload csv file).</li>
            </ul>
        </div>
    </div>
    <div class="box-2 glass-background">
        <div class="box-2--top">
            <h2>Necessity?</h2>
        </div>
        <div class="box-2--bottom">
            <p class="text">Now a days everyone has a cell phone in their pocket with basic features such as messaging and calling. Spam communications are those that are delivered to lot of people without their permission and usually promote products, facilities, or business possibilities. The proportion of fraudulent communications among spam has drastically grown in recent times. Fraud messages sometimes use a tempting or misleading offers to fool recipients into providing money or sensitive information.</p>
            <p class="text">One approach towards creating a system for scam sms recognition and early scam detection is identifying spam messages. AI enabled Natural Language Processing tools have seized control of the issue and found a solution by enabling us to distinguish between ham and spam text based on past data. Thanks to the technology make it to happen.</p>
        </div>
    </div>
</div>
{% endblock content %}

aiServices/templates/smsSpamClassification/predict.html
{% extends "global/layout.html" %} 

{% block predict %} 
    {% if showPredict %} 
        <a href="{{ url_for('smsSpamClassification.predict') }}" class="btn btn-invisible">Predict</a>
    {% else %} 
        <a href="{{ url_for('smsSpamClassification.predictBatch') }}" class="btn btn-invisible">Predict Batch</a>
    {% endif %}
{% endblock predict %}

{% block content %} 
<div class="sms-spam predict">
    <div class="box-1 glass-background">
        <div class="box-1--top">
            <a href="{{ url_for('smsSpamClassification.details') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                </svg>
            </a>
            <h2>SMS Ham-Spam Pediction</h2>
        </div>
        <div class="box-1--bottom">
            <!-- add needs-validation, novalidate inside below form  -->
            <form action="" method="post"> 
                {{ form.hidden_tag() }}
                <div class="text-box">
                    <label for="content">News Content</label>
                    {{ form.content }}
                    <!-- above line is same as below line -->
                    <!-- <textarea id="content" name="content" required></textarea> -->
                </div>
                <input name="submit" type="submit" value="Predict" class="btn btn-outline">
            </form>
        </div>
    </div>
    <div class="box-2 glass-background">
        <div class="box-2--top">
            <h2>Results</h2>
        </div>
        <div class="box-2--bottom">
            {% if show_output %}
                <p><span>{{ ham_score }}%</span>HAM</p>
                <p class="other"><span>{{ spam_score }}%</span>SPAM</p>
            {% else %} 
                <p class="default">output<br> will display here</p>
            {% endif %}
        </div>
    </div>
    
</div>
{% endblock content %}

aiServices/templates/smsSpamClassification/predictBatch.html
{% extends "global/layout.html" %} 

{% block predict %} 
    {% if showPredict %} 
        <a href="{{ url_for('smsSpamClassification.predict') }}" class="btn btn-invisible">Predict</a>
    {% else %} 
        <a href="{{ url_for('smsSpamClassification.predictBatch') }}" class="btn btn-invisible">Predict Batch</a>
    {% endif %}
{% endblock predict %}

{% block content %} 
<div class="sms-spam predict-batch">
    {% if not show_output %}
        <div class="box-1 glass-background">
            <div class="box-1--top">
                <a href="{{ url_for('smsSpamClassification.details') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                    </svg>
                </a>
                <h2>SMS Ham-Spam Pediction on Batch Mode</h2>
            </div>
            <div class="box-1--bottom">
                <!-- add  class="needs-validation" novalidate in the below form  -->
                <form action="" method="post" enctype="multipart/form-data"> 
                    {{ form.hidden_tag() }}
                    <label for="file_data">Upload CSV File</label>
                    {{ form.file_data }}
                    <div class="btn-box">
                        <input name="submit" type="submit" value="Predict Batch" class="btn btn-outline">
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <div class="box-1 glass-background results">
            <div class="box-1--top">
                <a href="{{ url_for('smsSpamClassification.predictBatch') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256S114.6 512 256 512s256-114.6 256-256zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z"/>
                    </svg>
                </a>
                <h2>Results</h2>
            </div>
            <div class="box-1--bottom">
                <p>download the csv file predicted on ham vs spam sms.</p>
                <div class="btn-box">
                    <a href="{{ url_for('main.download_file', file_name=output_file_name) }}" class="btn">Download</a>
                </div>
                <table>
                    <tr>
                        <th>Total Records</th>
                        <th>Spam Records</th>
                        <th>Ham Records</th>
                    </tr>
                    <tr>
                        <td>{{ spam_count + ham_count }}</td>
                        <td>{{ spam_count }}</td>
                        <td>{{ ham_count }}</td>
                    </tr>
                </table>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}